- include_vars: mysql.yml

- name: install mysql
  yum: pkg={{item}} state=installed
  with_items:
    - mysql
    - mysql-server
    - MySQL-python
  tags:
    - mysql installation

- name: starting mysql server
  service: name=mysqld state=started
  tags:
    - starting mysql service

- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql

- name: Create slow query log file (if configured).
  file: dest={{ mysql_slow_query_log_file }} state=touch
  when: mysql_slow_query_log_enabled

- name: Set ownership on slow query log file (if configured).
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0644
  when: mysql_slow_query_log_enabled

- name: setting up root password
  mysql_user: name={{mysql_root_user}}
              password={{ mysql_root_password }}
              check_implicit_admin=yes
              login_user={{mysql_root_user}}
              login_password=""
              state=present
  ignore_errors: True
  tags:
    - setting up root password

- name: creating dbs for myapplication
  mysql_db: name={{item.name}} 
            state=present 
            login_user={{mysql_root_user}}
            login_password={{mysql_root_password}}
  with_items: "{{ mysql_databases }}"

- name: setting up application user
  mysql_user: name={{item.name}}
              password={{item.secret}}
              check_implicit_admin=yes
              priv={{item.db}}.*:ALL
              login_user={{mysql_root_user}}
              login_password={{mysql_root_password}}
              state=present
  with_items: "{{ mysql_users }}"

- name: Get list of hosts for the anonymous user.
  command: mysql -p{{mysql_root_password}} -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous MySQL users.
  mysql_user:
     name=""
     host="{{ item }}"
     login_user={{mysql_root_user}}
     login_password={{mysql_root_password}}
     state=absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: Remove MySQL test database.
  mysql_db: name='test' 
            state=absent
            login_user={{mysql_root_user}}
            login_password={{mysql_root_password}}
