additional_packages_install: true
additional_packages:
  - openssl
  - ntp
  - open-vm-tools
  - nginx

additional_services_handler: true
additional_services:
  - {name: 'nginx', state: 'started' }
  - {name: 'vmtoolsd', state: 'started' }

configuration_to_be_setup: true
configuration_setup:
  - { name: 'nginx', src: 'default.conf', dest: '/etc/nginx/conf.d/default.conf', state: 'reloaded'}
